spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: your-id
            client-secret: your-secret
            scope:
              - read:user
              - user:email
          google:
            client-id: your-id
            client-secret: your-secret

  application:
    name: notes
  datasource:
    url: jdbc:mysql://localhost:3306/securenotes
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
  app:
    jwtSecret: mySecretKey123912738aopsgjnspkmndfsopkvajoirjg94gf2opfng2moknm
    jwtExpirationMs: 172800000
  mail:
    host: smtp.gmail.com
    port: 587
    username: your-mail@gmail.com
    password: xwjkaudwijgawdpz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
frontend:
  url: http://localhost:3000

logging:
  level.org:
    springframework:
      security: DEBUG
      orm.jpa.JpaBaseConfiguration: ERROR
    hibernate:
      SQL: OFF
      type.descriptor.sql.BasicBinder: OFF
      orm.deprecation: ERROR
      engine.transaction.jta.platform.internal.JtaPlatformInitiator: ERROR
